---

- name: Molecule | Verify | Default scenario
  hosts: all

  vars_files:
    - "../vars/main.yml"

  environment:
    - PATH: "{{ homebrew_search_paths | join(':') }}:{{ ansible_env.PATH }}"

  tasks:
    - name: Molecule | Verify | Include setup tasks
      ansible.builtin.include_tasks: "../tasks/setup.yml"
      tags:
        - always

...
