---

### Activity Monitor

- name: "Activity Monitor: Show the main window when launching app."
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: "{{ activity_monitor.show_main_window }}"
    state: present

- name: "Activity Monitor: Show all processes."
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0
    state: present

- name: "Activity Monitor: Sort Activity Monitor results by {{ activity_monitor.sort_by }}"
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortColumn
    type: string
    value: "{{ activity_monitor.sort_by }}"
    state: present

- name: "Activity Monitor: Sort Activity Monitor results by {{ activity_monitor.sort_by }} - Direction DSC"
  community.general.osx_defaults:
    domain: com.apple.ActivityMonitor
    key: SortDirection
    type: int
    value: "{{ activity_monitor.sort_direction }}"
    state: present

### Mail

- name: "Mail: Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app."
  community.general.osx_defaults:
    domain: com.apple.mail
    key: AddressesIncludeNameOnPasteboard
    type: bool
    value: "{{ mail.use_advanced_copy_format }}"
    state: present

### Photos

- name: "Photos: Prevent Photos from opening automatically when devices are plugged in."
  community.general.osx_defaults:
    domain: com.apple.ImageCapture
    key: disableHotPlug
    type: bool
    value: "{{ photos.disable_hotplug }}"
    state: present
