---

- name: Dock - Enable spring loading for all Dock items.
  community.general.osx_defaults:
    domain: com.apple.dock
    key: enable-spring-load-actions-on-all-items
    type: bool
    value: "{{ dock.enable_spring_load_everywhere }}"
    state: present

- name: Dock - Don’t show recent applications in Dock.
  community.general.osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: "{{ dock.show_recents }}"
    state: present

- name: Dock - Bottom left screen corner → Start screen saver (corner).
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-corner
    type: int
    value: "{{ dock.bottom_left_corner }}"
    state: present

- name: Dock - Bottom left screen corner → Start screen saver (modifier).
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-bl-modifier
    type: int
    value: "{{ dock.bottom_left_modifier }}"
    state: present

- name: Dock - Bottom right screen corner → Launchpad (corner).
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-br-corner
    type: int
    value: "{{ dock.bottom_right_corner }}"
    state: present

- name: Dock - Bottom right screen corner → Launchpad (modifier).
  community.general.osx_defaults:
    domain: com.apple.dock
    key: wvous-br-modifier
    type: int
    value: "{{ dock.bottom_right_modifier }}"
    state: present

- name: Dock - Mission Control - Speed up animations.
  community.general.osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: "{{ dock.expose_animation_duration }}"
    state: present
