---

- name: Finder - Allow quitting via ⌘ + Q; doing so will also hide desktop icons.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: QuitMenuItem
    type: bool
    value: "{{ finder.allow_quitting }}"
    state: present

- name: Finder - Set new path as the default location for new Finder windows.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "{{ finder.new_window_target }}"
    state: present

- name: Finder - Set new path as the default location for new Finder windows.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "{{ finder.new_window_target_path }}"
    state: present

- name: Finder - Change current search scope for all new searches.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "{{ finder.search_scope }}"
    state: present

- name: Finder - Change finder view in all windows by default.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "{{ finder.view_mode }}"
    state: present

- name: "Finder - Show path bar in Finder (Example: 751 items ... 351 GB left ...)."
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: "{{ finder.show_path_bar }}"
    state: present

- name: Finder - Keep folders on top when sorting by name.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXSortFoldersFirst
    type: bool
    value: "{{ finder.keep_folders_on_top }}"
    state: present

- name: Finder - Disable the warning when changing a file extension.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXEnableExtensionChangeWarning
    type: bool
    value: "{{ finder.disable_extension_change_warning | ternary(false,true) }}"
    state: present

- name: Finder - Show status bar.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: "{{ finder.show_status_bar }}"
    state: present

- name: Finder - Show bottom path bar by default.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: "{{ finder.show_bottom_path_bar }}"
    state: present

- name: Finder - Avoid creating .DS_Store files on network volumes.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: DSDontWriteNetworkStores
    type: bool
    value: "{{ finder.avoid_dsstore_on_network_volumes }}"
    state: present

- name: Finder - Avoid creating .DS_Store files on USB volumes.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: DSDontWriteUSBStores
    type: bool
    value: "{{ finder.avoid_dsstore_on_usb_volumes }}"
    state: present

- name: Finder - Disable the warning before emptying the Trash.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: WarnOnEmptyTrash
    type: bool
    value: "{{ finder.disable_trash_warning | ternary(false,true) }}"
    state: present

- name: Finder - Display full POSIX path as Finder window title.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    type: bool
    value: "{{ finder.show_full_title }}"
    state: present

- name: Finder - Show all filename extensions.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: "{{ finder.show_all_file_exts }}"
    state: present

- name: "Finder - Expand the following File Info panes: General, Open With, Sharing & Permissions."
  ansible.builtin.shell: >
    defaults write com.apple.finder FXInfoPanesExpanded -dict \
      MetaData -bool true \
      General -bool true \
      OpenWith -bool true \
      Privileges -bool true
  changed_when: false
  when: finder.expand_fileinfo_panels

- name: Finder - Show icons for external hard drives on Desktop.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: "{{ finder.desktop_show_ext_hard_drives }}"
    state: present

- name: Finder - Show icons for hard drives on Desktop.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: "{{ finder.desktop_show_hard_drives }}"
    state: present

- name: Finder - Show icons for mounted servers on Desktop.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: "{{ finder.desktop_show_mounted_servers }}"
    state: present

- name: Finder - Show icons for removable media on Desktop.
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: "{{ finder.desktop_show_removable_media }}"
    state: present

- name: Finder - Show the ~/Library folder in finder.
  ansible.builtin.shell: >
    chflags nohidden ~/Library
  changed_when: false
  become: true
  when: finder.unhide_library_folder

- name: Finder - Show the ~/Library folder in finder - remove xattr attrs
  community.general.xattr:
    path: ~/Library
    key: com.apple.FinderInfo
    state: absent
  when: finder.unhide_library_folder
  become: true

- name: Finder - Show the ~/Users folder in finder.
  ansible.builtin.shell: >
    chflags nohidden /Users
  changed_when: false
  become: true
  when: finder.unhide_users_folder

- name: Finder - Change which programs will open the given file types.
  block:
    - name: Finder - Installing duti - command-line tool to select default applications for document types Mac OS X.
      community.general.homebrew:
        name: duti
        state: installed

    - name: Finder - Prefer custom editor over default TextEdit for plain text files.
      ansible.builtin.shell: >
        duti -s {{ finder.default_editor }} public.data all; \
        duti -s {{ finder.default_editor }} public.plain-text all
      changed_when: false
  when: finder.install_duti
