---

- name: "Using scutil to set HostName, ComputerName, and LocalHostName."
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: change_hostname

- name: "Write new hostname to SMB server."
  community.general.osx_defaults:
    domain: /Library/Preferences/SystemConfiguration/com.apple.smb.server
    key: NetBIOSName
    type: string
    value: "{{ hostname }}"
    state: present
  when: change_hostname
  become: true

- name: "Expand save panel by default."
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode # NSNavPanelExpandedStateForSaveMode2 deprecated?
    type: bool
    value: "{{ general_expand_save_panel }}"
    state: present

- name: "Expand print panel by default."
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint # PMPrintingExpandedStateForPrint2 deprecated?
    type: bool
    value: "{{ general_expand_print_panel }}"
    state: present

- name: "Automatically quit printer app once the print jobs complete."
  community.general.osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: "{{ general_quit_print_job }}"
    state: present

- name: "Reveal IP address, hostname, OS version, etc. when clicking the clock in the login window (only)."
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: AdminHostInfo
    type: string
    value: HostName
    state: present
  become: true
  when: general_login_clock_click_hostname

- name: "Add iOS Simulator to Launchpad."
  ansible.builtin.file:
    src: "/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app"
    dest: "/Applications/Simulator.app"
    owner: "{{ remote_regular_user }}"
    group: staff
    state: link
  when: general_create_simulator_symlink
