---

### Keyboard

# Fn key is used for special features.
- name: Use F1, F2, etc. keys as standard function keys on external keyboards each key.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.keyboard.fnState
    type: int
    value: 1
    state: present
  when: input_fkeys_as_primary

- name: Pressing Fn key shows Emoji keyboard.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleFnUsageType
    type: int
    value: 2
    state: present
  when: input_fnkey_shows_emoji

### Text

- name: Disable text auto-correction in native apps.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: "{{ input_disable_auto_correction | ternary(false,true) }}"
    state: present

- name: Disable auto-correction in web.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: WebAutomaticSpellingCorrectionEnabled
    type: bool
    value: "{{ input_disable_web_auto_correction | ternary(false,true) }}"
    state: present

- name: Do not disable smart quotes, but set them as simple one's, instead of smart.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSUserQuotesArray
    type: array
    value:
      - '\U0022'
      - '\U0022'
      - '\U0027'
      - '\U0027'
  changed_when: false
  when: input_use_simple_quotes

### Mouse

- name: Disable natural scroll for mouse and trackpad.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: "{{ input_use_native_macos_scroll }}"
    state: present

- name: Magic mouse should run in two button mode.
  block:
    - name: Magic mouse should run in two button mode.
      community.general.osx_defaults:
        domain: com.apple.AppleMultitouchMouse
        key: MouseButtonMode
        type: string
        value: TwoButton
        state: present

    - name: Bluetooth Magic mouse should run in two button mode.
      community.general.osx_defaults:
        domain: com.apple.driver.AppleBluetoothMultitouch.mouse
        key: MouseButtonMode
        type: string
        value: TwoButton
        state: present
  when: input_mouse_two_button_mode

- name: Magic mouse - enable double tap gesture for zoom.
  block:
    - name: Magic mouse - enable double tap gesture for zoom.
      community.general.osx_defaults:
        domain: com.apple.AppleMultitouchMouse
        key: MouseOneFingerDoubleTapGesture
        type: int
        value: 1
        state: present

    - name: Bluetooth Magic mouse - enable double tap gesture for zoom.
      community.general.osx_defaults:
        domain: com.apple.driver.AppleBluetoothMultitouch.mouse
        key: MouseOneFingerDoubleTapGesture
        type: int
        value: 1
        state: present
  when: input_mouse_double_tap_gesture

### Trackpad

- name: Enabling trackpad controls.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ContextMenuGesture
    type: int
    value: 1
    state: present


- name: Map bottom right corner to right-click for integrated trackpad r1.
  block:
    - name: Apply rule 1.
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.trackpad.trackpadCornerClickBehavior
        type: int
        value: 1
        state: present

    - name: Apply rule 2.
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.trackpad.enableSecondaryClick
        type: bool
        value: true
        state: present
  when: input_bottom_right_click_trackpad

- name: Map bottom right corner to right-click for bluetooth trackpad.
  block:
    - name: Apply rule 1.
      community.general.osx_defaults:
        domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
        key: TrackpadCornerSecondaryClick
        type: int
        value: 2
        state: present

    - name: Apply rule 2.
      community.general.osx_defaults:
        domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
        key: TrackpadRightClick
        type: bool
        value: true
        state: present
  when: input_bottom_right_click_bt_trackpad

### Shortcuts

- name: Allow global app shortcuts.
  community.general.osx_defaults:
    domain: com.apple.universalaccess
    key: com.apple.custommenu.apps
    type: array
    value:
      - NSGlobalDomain
  changed_when: false
  when: input_allow_global_app_shortcuts

- name: "⌥⌘, brings up System Preferences dialog (opt+cmd+comma)"
  ansible.builtin.shell: >
    defaults write "Apple Global Domain" NSUserKeyEquivalents -dict-add "System Preferences\\U2026" "@~,"
  changed_when: false
  when: input_shortcut_opt_cmd_comma
