---

# Language and Region

# Set the timezone; see `sudo systemsetup -listtimezones` for other values
- name: Set timezone to Europe/Riga
  community.general.timezone:
    name: Europe/Riga
  become: true

- name: Set main languages - English US, Latvian - LV, Latvian - RU.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - en-US
      - lv-LV
      - ru-LV
    state: present

- name: Set system locale - US English with EUR as main currency.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: "en_US@currency=EUR"
    state: present

- name: Set metric measurment units.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: true
    state: present

- name: Measurments in centimeters.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: "Centimeters"
    state: present

- name: Enables the input menu in the menu bar.
  community.general.osx_defaults:
    domain: com.apple.TextInputMenu
    key: visible
    type: bool
    value: true
    state: present

# https://github.com/claco/ansible/commit/34573922350fe18b4f02d2e4fb7cf8decbce2c0a
# https://github.com/ansible/ansible/issues/24028
# Add input sources - Latvian and Russian - Phonetic
# defaults write com.apple.HIToolbox AppleEnabledInputSources -array-add '<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>19457</integer><key>KeyboardLayout Name</key><string>Russian - Phonetic</string></dict>'
# defaults write com.apple.HIToolbox AppleEnabledInputSources -array-add '<dict><key>InputSourceKind</key><string>Keyboard Layout</string><key>KeyboardLayout ID</key><integer>30765</integer><key>KeyboardLayout Name</key><string>Latvian</string></dict>'
