---

# Language and Region

- name: Set timezone to Europe/Riga
  community.general.timezone:
    name: "{{ lng_timezone }}"
  become: true

- name: Set main languages.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value: "{{ lng_languages }}"
    state: present

- name: Set system locale - US English with EUR as main currency.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: "{{ lng_locale }}"
    state: present

- name: Set metric measurement units.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: "{{ lng_metric_units }}"
    state: present

- name: Measurments in centimeters.
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: "{{ lng_apple_units }}"
    state: present

- name: Enables the input menu in the menu bar.
  community.general.osx_defaults:
    domain: com.apple.TextInputMenu
    key: visible
    type: bool
    value: "{{ lng_inputs_in_status_bar }}"
    state: present
