---

- include_tasks: applications.yml
  tags:
    - applications
    - configureapplications

- include_tasks: battery.yml
  tags:
    - battery
    - batterysaving
    - configurebattery

- include_tasks: dock.yml
  tags:
    - dock
    - configuredock

- include_tasks: finder.yml
  tags:
    - finder
    - configurefinder

- include_tasks: general.yml
  tags:
    - general
    - configuregeneral

- include_tasks: input.yml
  tags:
    - mouse
    - trackpad
    - keyboard
    - configurekeyboard
    - configureinput

- include_tasks: lang.yml
  tags:
    - lang
    - configurelang

- include_tasks: safari.yml
  tags:
    - safari
    - configuresafari

- include_tasks: screen.yml
  tags:
    - screen
    - configurescreen

- include_tasks: security.yml
  tags:
    - security
    - configuresecurity
