---

- include_tasks: applications.yml
  tags:
    - applications
    - configureapplications

- include_tasks: dock.yml
  tags:
    - dock
    - configuredock

- include_tasks: finder.yml
  tags:
    - finder
    - configurefinder

- include_tasks: input.yml
  tags:
    - input
    - configureinput

- include_tasks: lang.yml
  tags:
    - lang
    - configurelang

- include_tasks: network.yml
  tags:
    - network
    - configurenetwork

- include_tasks: power.yml
  tags:
    - power
    - configurepower

- include_tasks: safari.yml
  tags:
    - safari
    - configuresafari

- include_tasks: screensaver.yml
  tags:
    - screensaver
    - configurescreensaver

- include_tasks: screenshots.yml
  tags:
    - screenshots
    - configurescreenshots

- include_tasks: security.yml
  tags:
    - security
    - configuresecurity

- include_tasks: ui.yml
  tags:
    - ui
    - configureui
