---

# @todo: Move out to molecule
- name: Maccfg | Include | Github Actions CI fixer tasks
  ansible.builtin.include_tasks: ci-cleaner.yml
  tags:
    - maccfg-ci-cleaner
  when: lookup('env', 'CI') | length > 0

- name: Maccfg | Include | Configure Applications
  ansible.builtin.include_tasks: applications.yml
  tags:
    - maccfg-applications

- name: Maccfg | Include | Configure Dock
  ansible.builtin.include_tasks: dock.yml
  tags:
    - maccfg-dock

- name: Maccfg | Include | Configure Finder
  ansible.builtin.include_tasks: finder.yml
  tags:
    - maccfg-finder

- name: Maccfg | Include | Configure input settings
  ansible.builtin.include_tasks: input.yml
  tags:
    - maccfg-input

- name: Maccfg | Include | Configure language settings
  ansible.builtin.include_tasks: lang.yml
  tags:
    - maccfg-lang

- name: Maccfg | Include | Configure network settings
  ansible.builtin.include_tasks: network.yml
  tags:
    - maccfg-network

- name: Maccfg | Include | Configure power settings
  ansible.builtin.include_tasks: power.yml
  tags:
    - maccfg-power

- name: Maccfg | Include | Configure Safari brower
  ansible.builtin.include_tasks: safari.yml
  tags:
    - maccfg-safari

- name: Maccfg | Include | Configure screensaver
  ansible.builtin.include_tasks: screensaver.yml
  tags:
    - maccfg-screensaver

- name: Maccfg | Include | Configure screenshot capturing
  ansible.builtin.include_tasks: screenshots.yml
  tags:
    - maccfg-screenshots

- name: Maccfg | Include | Configure security settings
  ansible.builtin.include_tasks: security.yml
  tags:
    - maccfg-security

- name: Maccfg | Include | Configure UI settings
  ansible.builtin.include_tasks: ui.yml
  tags:
    - maccfg-ui

...
