---

- name: "Using scutil to set HostName, ComputerName, and LocalHostName."
  ansible.builtin.hostname:
    name: "{{ network.hostname }}"
  when: network.change_hostname

- name: "Write new hostname to SMB server."
  community.general.osx_defaults:
    domain: /Library/Preferences/SystemConfiguration/com.apple.smb.server
    key: NetBIOSName
    type: string
    value: "{{ network.hostname }}"
    state: present
  when: network.change_hostname
  become: true
