---

### Safari
# defaults write com.apple.Safari UserStyleSheetEnabled -bool false

- name: Magic mouse should run in two button mode.
  block:
    - name: "Safari: Enable Develop menu and the Web Inspector in Safari 14+ - Inspect Menu"
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: WebKitDeveloperExtrasEnabledPreferenceKey
        type: bool
        value: true
        state: present

    - name: "Safari: Enable Develop menu and the Web Inspector in Safari 14+"
      community.general.osx_defaults:
        domain: com.apple.Safari
        key: WebKitPreferences.developerExtrasEnabled
        type: bool
        value: true
        state: present
  when: safari_web_inspector

- name: "Safari: Change default homepage"
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: HomePage
    type: string
    value: "{{ safari_homepage }}"
    state: present

- name: "Safari: Show homepage instead of Start Page when opening new tab"
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: NewTabBehavior
    type: bool
    value: "{{ safari_show_homepage_in_new_tabs | ternary(false,true) }}"
    state: present

- name: "Safari: Show homepage instead of Start Page when opening new window"
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: NewWindowBehavior
    type: bool
    value: "{{ safari_show_homepage_in_new_windows | ternary(false,true) }}"
    state: present

# @todo Add to readme.md as post install instruction
# You will have to manually give full disk access to terminal/iterm to do that
# Enable Safari’s debug menu
# Go to System Preferences -> Security & Privacy -> Full Disk Access -> Click on iTerm2
# defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
