---

### Screen

- name: "Require password when screen awakes."
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
    state: present

- name: "Require password immediately after sleep or screen saver begins"
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0
    state: present

### Screenshots

- name: "Screenshots: Save to custom folder instead of Desktop."
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "~/Screenshots"
    state: present

- name: "Screenshots: Change the default file name."
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: name
    type: string
    value: "src"
    state: present
