---

- name: Screenshots - Save to custom folder instead of Desktop
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "{{ maccfg_screenshots_directory }}"
    state: present

- name: Screenshots - Change the default file name prefix
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: name
    type: string
    value: "{{ maccfg_screenshots_use_prefix }}"
    state: present

...
