---

### Screen

- name: Security - Screen - Require password when screen awakes.
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
    state: present
  when: security.screen.require_pass_after_awake
  changed_when: false

- name: Security - Screen - Require password immediately after sleep or screen saver begins.
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: "{{ security.screen.require_pass_delay }}"
    state: present
  changed_when: false

### Privacy

- name: Security - Privacy / Feedback Assistant - Turn off Feedback Assistant data auto-gathering.
  community.general.osx_defaults:
    domain: com.apple.appleseed.FeedbackAssistant
    key: Autogather
    type: bool
    value: "{{ security.privacy.apple_feedback_assistant }}"
    state: present

- name: Security - Privacy / Advertising - Disable Personalized Ads.
  community.general.osx_defaults:
    domain: com.apple.AdLib
    key: allowApplePersonalizedAdvertising
    type: int
    value: 0
    state: present
  when: security.privacy.disable_personalized_ads

### Firewall

# Alternative way
# https://github.com/rgcr/m-cli - utility allow to restart firewall without
# unloading/loading plist
# $ m firewall status; m firewall [enable|disable]
#
- name: Security - Firewall - Setting to run in {{ security.firewall.mode }} mode.
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.alf
    key: globalstate
    type: int
    value: "{{ security.firewall.mode }}"
    state: present
  become: true

### Software Updates

- name: Security - Software Updates - Check for updates each {{ security.updates.delay_days }} days.
  community.general.osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: "{{ security.updates.delay_days }}"
    state: present

### Firevault

- name: Security - Enable Firevault
  firevault:
    enabled: "{{ security.firevault.enabled }}"
  when: security.firevault.enabled
