---

### Screen

- name: Security - Screen - Require password when screen awakes
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: 1
    state: present
  when: maccfg_security_require_pass_after_awake
  changed_when: false

- name: Security - Screen - Require password immediately after sleep or screen saver begins
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: "{{ maccfg_security_require_pass_delay }}"
    state: present
  changed_when: false

### Privacy

- name: Security - Privacy / Feedback Assistant - Turn off Feedback Assistant data auto-gathering
  community.general.osx_defaults:
    domain: com.apple.appleseed.FeedbackAssistant
    key: Autogather
    type: bool
    value: "{{ maccfg_privacy_apple_feedback_assistant }}"
    state: present

- name: Security - Privacy / Advertising - Disable Personalized Ads
  community.general.osx_defaults:
    domain: com.apple.AdLib
    key: allowApplePersonalizedAdvertising
    type: int
    value: 0
    state: present
  when: maccfg_privacy_disable_personalized_ads

### Firewall

# Alternative way
# https://github.com/rgcr/m-cli - utility allow to restart firewall without
# unloading/loading plist
# $ m firewall status; m firewall [enable|disable]
#
- name: Security - Firewall - Setting to run in {{ maccfg_firewall_mode }} mode
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.alf
    key: globalstate
    type: int
    value: "{{ maccfg_firewall_mode }}"
    state: present
  become: true
  become_user: root

### Software Updates

- name: Security - Software Updates - Check for updates each {{ maccfg_updates_delay_days }} days
  community.general.osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: "{{ maccfg_updates_delay_days }}"
    state: present

### Firevault

- name: Security - Ensure Firevault is enabled
  firevault:
    enabled: "{{ maccfg_firevault_enabled }}"
  when: maccfg_firevault_enabled

...
